# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bf6b1b76f1feff71a48f44ea80254f07d28784fa566a69de14159f671a566066165d4bfafe0c2be1f0d7151a93121689d21cb65b852b3ce5840f7fc62f9e20ad

test:
  secret_key_base: 26501355298692815b75ab95299eb44c92dfaf676c7e083cb6c5371991915856cc47b6eb953c8d88a99f6b5af78d64db579d642e4a035e413c513868d26ec432

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
